output_dir: './saved_result'

optimizers: ['COBYLA']
num_cities_list: [2, 3]
penalty_weight: 0.01
use_simulator: true
shots: 2000
max_iter: 100


instance: 'crn:v1:bluemix:public:quantum-computing:us-east:a/0d5f2945f5c44fd6a69d8a9dd034808c:2e832f3b-b7a7-466c-b735-53a9ed77d94b::'
token: '0oZvOcWcHiCTQyyGO1fs-1AwZREj7PFl3K2CoYl7fkTX'
